const fs=require('fs'),http=require('http'),path=require('path'),{spawn}=require('child_process');
const root=process.cwd(), out=path.join(root,'tests/bank-audit/evidence');
let html=fs.readFileSync('Tofinancehtml/bank-audit-analyzer.html','utf8').replace(/<script[\s\S]*?<\/script>/g,'').replaceAll('../images/','/images/');
let ui=fs.readFileSync('Tojs/bank-audit/bank_audit_ui.js','utf8');
ui=ui.slice(0,ui.indexOf('  document.addEventListener("DOMContentLoaded"'))+`global.renderPreview=(audit)=>{state.readOnly=true;renderAudit(audit);bindTabs();};})(window);`;
const script=['crdb','engine'].map(n=>fs.readFileSync(`Tojs/bank-audit/bank_audit_${n}.js`,'utf8')).join('\n');
const pdfCode=fs.readFileSync('Tojs/bank-audit/bank_audit_pdf.js','utf8');
const fixture=fs.readFileSync('tests/bank-audit/reconstructed-september.txt','utf8');
html=html.replace('</body>',`<script>${script}\n${ui}\n${pdfCode}\nconst parsed=SomapCrdb.parsePages([${JSON.stringify(fixture)}]);window.audit={...SomapBankAuditEngine.analyze(parsed.rows,{meta:parsed.meta}),bankName:'CRDB',schoolName:'RECONSTRUCTED TEST FIXTURE',uploadedFileName:'Acceptance specification — not original PDF',statementPeriodFrom:'2026-09-01',statementPeriodTo:'2026-09-03',parserMeta:parsed.meta};renderPreview(audit);document.getElementById('schoolName').textContent='RECONSTRUCTED TEST FIXTURE';document.getElementById('parseStatus').textContent='Local test preview — original PDF verification pending';document.getElementById('userRole').textContent='Test';</script></body>`);
const server=http.createServer((req,res)=>{if(req.url==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');res.end(html);}else {const p=path.resolve(root,'.'+req.url);if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(p,(e,b)=>{if(e)res.writeHead(404).end();else res.end(b);});}});
(async()=>{await new Promise(r=>server.listen(8765,'127.0.0.1',r));
const edge=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=9223','--user-data-dir='+path.join(out,'browser-profile'),'about:blank'],{windowsHide:true,stdio:'ignore'});
let target;for(let i=0;i<40;i++){try{target=(await(await fetch('http://127.0.0.1:9223/json')).json()).find(t=>t.type==='page' && !t.url.startsWith('chrome-extension:'));if(target)break;}catch{}await new Promise(r=>setTimeout(r,250));}
if(!target)throw Error('Browser did not start');
const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map();ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const pair=pending.get(m.id);pending.delete(m.id);m.error?pair[1](m.error):pair[0](m.result);}});const call=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,[resolve,reject]);ws.send(JSON.stringify({id,method,params}));});
try{await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url:'http://127.0.0.1:8765/'});for(let i=0;i<40;i++){const r=await call('Runtime.evaluate',{expression:'!!window.audit'});if(r.result.value)break;await new Promise(r=>setTimeout(r,100));}
for(const tab of ['summary','income','withdrawals','review']){await call('Runtime.evaluate',{expression:`document.querySelector('[data-tab="${tab}"]').click()`});const shot=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});fs.writeFileSync(path.join(out,tab+'.png'),Buffer.from(shot.data,'base64'));}
await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await call('Runtime.evaluate',{expression:`document.querySelector('[data-tab="income"]').click()`});const shot=await call('Page.captureScreenshot',{format:'png'});fs.writeFileSync(path.join(out,'mobile.png'),Buffer.from(shot.data,'base64'));
const pdfResult = await call('Runtime.evaluate',{expression:`(async()=>{for(const src of ['https://cdn.jsdelivr.net/npm/jspdf@2.5.1/dist/jspdf.umd.min.js','https://cdn.jsdelivr.net/npm/jspdf-autotable@3.8.2/dist/jspdf.plugin.autotable.min.js'])await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});const doc=await SomapBankAuditPdf.createDocument(audit);return {pdf:doc.output('datauristring').split(',')[1],pages:doc.getNumberOfPages()};})()`,awaitPromise:true,returnByValue:true});
if(pdfResult.exceptionDetails)throw Error(JSON.stringify(pdfResult.exceptionDetails));
fs.writeFileSync(path.join(out,'reconstructed-september-report.pdf'),Buffer.from(pdfResult.result.value.pdf,'base64'));
await call('Runtime.evaluate',{expression:`(async()=>{await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const doc=await SomapBankAuditPdf.createDocument(audit);window.renderedPdf=await pdfjsLib.getDocument({data:new Uint8Array(doc.output('arraybuffer')),useSystemFonts:false,disableFontFace:true,standardFontDataUrl:'https://cdn.jsdelivr.net/npm/pdfjs-dist@3.11.174/standard_fonts/'}).promise;})()`,awaitPromise:true});
const fullPage=await call('Runtime.evaluate',{expression:`(async()=>{const p=await renderedPdf.getPage(6),v=p.getViewport({scale:1.5}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;return c.toDataURL().split(',')[1]})()`,awaitPromise:true,returnByValue:true});fs.writeFileSync(path.join(out,'pdf-page-6-full.png'),Buffer.from(fullPage.result.value,'base64'));
for(let start=1;start<=pdfResult.result.value.pages;start+=12){
 const result=await call('Runtime.evaluate',{expression:`(async()=>{const canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1720;const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);for(let n=`+start+`;n<Math.min(`+(start+12)+`,renderedPdf.numPages+1);n++){const p=await renderedPdf.getPage(n),v=p.getViewport({scale:0.48}),c=document.createElement('canvas');c.width=v.width;c.height=v.height;await p.render({canvasContext:c.getContext('2d'),viewport:v}).promise;const i=n-`+start+`,x=(i%4)*300,y=Math.floor(i/4)*570;ctx.drawImage(c,x,y);ctx.fillStyle='black';ctx.font='16px sans-serif';ctx.fillText('Page '+n,x+10,y+425);}return canvas.toDataURL('image/png').split(',')[1];})()`,awaitPromise:true,returnByValue:true});
 if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));fs.writeFileSync(path.join(out,'pdf-pages-'+start+'.png'),Buffer.from(result.result.value,'base64'));
}
console.log('Saved reconstructed-fixture screenshots and PDF ('+pdfResult.result.value.pages+' pages) to '+out);
}finally{await call('Browser.close').catch(()=>{});ws.close();server.close();edge.kill();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});


