const fs=require('fs'),path=require('path'),http=require('http'),{spawn}=require('child_process');
const root=process.cwd(),out=path.join(root,'tests/bank-audit/evidence/actual');
const server=http.createServer((req,res)=>{const p=path.resolve(root,'.'+decodeURIComponent(req.url.split('?')[0]));if(!p.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(p,(e,b)=>{if(e)res.writeHead(404).end();else {res.setHeader('Content-Type',p.endsWith('.html')?'text/html; charset=utf-8':p.endsWith('.js')?'text/javascript':p.endsWith('.pdf')?'application/pdf':'application/octet-stream');res.end(b);}});});
(async()=>{await new Promise(r=>server.listen(8766,'127.0.0.1',r));const edge=spawn('C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=9224','--user-data-dir='+path.join(out,'browser-profile'),'about:blank'],{windowsHide:true,stdio:'ignore'});
let target;for(let i=0;i<50;i++){try{target=(await(await fetch('http://127.0.0.1:9224/json',{signal:AbortSignal.timeout(500)})).json()).find(t=>t.type==='page');if(target)break;}catch{}await new Promise(r=>setTimeout(r,200));}if(!target){edge.kill();server.close();throw Error('Browser not available');}
const ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r,{once:true}));let id=0;const pending=new Map();ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);if(p){clearTimeout(p[2]);pending.delete(m.id);m.error?p[1](m.error):p[0](m.result);}}});const call=(method,params={})=>new Promise((resolve,reject)=>{const key=++id;pending.set(key,[resolve,reject,setTimeout(()=>{pending.delete(key);reject(Error('Timeout: '+method));},45000)]);ws.send(JSON.stringify({id:key,method,params}));});
try {await call('Page.navigate',{url:'http://127.0.0.1:8766/tests/bank-audit/fixtures/september-original.pdf'});await call('Runtime.evaluate',{expression:`location.href='http://127.0.0.1:8766/tests/bank-audit/inspect.html'`});await new Promise(r=>setTimeout(r,500));
const result=await call('Runtime.evaluate',{expression:`(async()=>{async function load(src){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s);});}await load('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js');await load('/Tojs/bank-audit/bank_audit_crdb.js');pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';const pdf=await pdfjsLib.getDocument({data:await(await fetch('/tests/bank-audit/fixtures/september-original.pdf')).arrayBuffer()}).promise;const pages=[];for(let n=1;n<=pdf.numPages;n++){const page=await pdf.getPage(n),content=await page.getTextContent();pages.push({page:n,rotate:page.rotate,view:page.view,viewport:page.getViewport({scale:1}).transform,items:content.items.map((x,i)=>({...x,index:i})),oldLines:SomapCrdb.logicalPage(content.items)});}return {pages,oldResult:SomapCrdb.parsePages(pages.map(p=>p.oldLines))};})()`,awaitPromise:true,returnByValue:true});
if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));fs.writeFileSync(path.join(out,'pdfjs-before.json'),JSON.stringify(result.result.value,null,2));console.log(JSON.stringify({pages:result.result.value.pages.map(p=>({page:p.page,rotate:p.rotate,view:p.view,viewport:p.viewport,items:p.items.length,sample:p.items.slice(0,10),oldLines:p.oldLines.slice(0,2000)})),oldRows:result.result.value.oldResult.rows.length}));
}finally{await call('Browser.close').catch(()=>{});ws.close();server.close();edge.kill();}
})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
