(function(){'use strict';const V=SomapVolunteers;let records={};let currentFilter='';const $=id=>document.getElementById(id);const fields=['firstName','middleName','lastName','otherName','gender','dateOfBirth','country','passportNumber','organization','countryCode','rawPhone','email','emergencyContact','volunteerType','volunteerTypeOther','specialty','specialtyOther','professionOrStudentStatus','institution','course','studentLevel','skills','strengths','childBenefit','languages','previousExperience','notes','plannedArrivalDate','plannedDepartureDate','actualArrivalDate','actualDepartureDate','status','assignedContact','accommodationNotes','visitPurpose','plannedActivities','accessEnabled','accessLevel','archiveAccessAllowed','accessExpiresAt'];
const phoneCss=document.createElement('link');phoneCss.rel='stylesheet';phoneCss.href='https://cdn.jsdelivr.net/npm/intl-tel-input@28.0.0/build/css/intlTelInput.css';document.head.appendChild(phoneCss);
fields.push('gmail','facebookName','instagramName','xName','linkedInName','socialMediaConsent');
const types=['Current volunteer','Expected volunteer','Past volunteer','Exchange visitor','Student volunteer','Professional volunteer','Project volunteer','Sponsorship-linked volunteer','Organization partner','Short-term visitor','Long-term volunteer','Other'];const specs=['Teaching support','English reading','Mathematics support','Science support','Computer/ICT','Coding/technology','Sports/games','Music','Arts/drawing','Counselling/mentorship','Library/reading','Health/first aid','Construction/project support','Photography/media','Administration','Fundraising coordination','Child sponsorship support','Cultural exchange','Environment/gardening','Other'];
const phonePicker=window.intlTelInput?window.intlTelInput($('rawPhone'),{initialCountry:'tz',countrySearch:true,separateDialCode:true,preferredCountries:['tz','ke','ug','rw','za','gb','de','us']}):null;
const fallbackCountries=window.SomapWorldCountries||[];
const libraryCountries=window.intlTelInput?.getCountryData?.()||[];const countries=libraryCountries.length?libraryCountries:fallbackCountries;
$('countryCode').innerHTML=countries.map(c=>`<option value="+${c.dialCode}">${c.flag||countryFlag(c)} +${c.dialCode} · ${V.escapeHtml(c.name)}</option>`).join('');
const countryList=document.createElement('datalist');countryList.id='allVolunteerCountries';countryList.innerHTML=countries.map(c=>`<option value="${V.escapeHtml(c.name)}">+${c.dialCode||''}</option>`).join('');document.body.appendChild(countryList);$('country').setAttribute('list',countryList.id);$('country').setAttribute('autocomplete','country-name');$('country').placeholder='Start typing, e.g. Kenya';
function countryFlag(c){return c.flag||(c.iso2?String.fromCodePoint(...c.iso2.toUpperCase().split('').map(x=>127397+x.charCodeAt(0))):'')}function showCountry(c){if(!c?.dialCode)return;$('countryCode').value=`+${c.dialCode}`;$('countryStatus').textContent=`${countryFlag(c)} ${c.name} · +${c.dialCode}`;$('countryStatus').classList.remove('hidden');phonePreview()}
function selectTypedCountry(){const aliases={kenyan:'kenya',tanzanian:'tanzania',ugandan:'uganda',rwandan:'rwanda',german:'germany',british:'united kingdom',american:'united states',canadian:'canada',french:'france',dutch:'netherlands'};const typed=$('country').value.trim().toLowerCase(),value=aliases[typed]||typed;const exact=countries.find(c=>c.name.toLowerCase()===value);const starts=countries.filter(c=>value&&c.name.toLowerCase().startsWith(value));const match=exact||(starts.length===1?starts[0]:null);if(match){$('country').value=match.name;phonePicker?.setSelectedCountry?.(match.iso2);showCountry(match)}return match}
$('country').addEventListener('input',selectTypedCountry);$('country').addEventListener('change',selectTypedCountry);
$('emergencyContact').closest('div').insertAdjacentHTML('afterend','<div class="span-3"><label>Gmail address (optional)</label><input id="gmail" type="email" placeholder="name@gmail.com"><div class="hint">Used only for school updates if provided.</div></div><div class="span-3"><label>Facebook name (optional)</label><input id="facebookName" placeholder="Profile or page name"></div><div class="span-3"><label>Instagram name (optional)</label><input id="instagramName" placeholder="@username"></div><div class="span-3"><label>X name (optional)</label><input id="xName" placeholder="@username"></div><div class="span-3"><label>LinkedIn name (optional)</label><input id="linkedInName" placeholder="Profile name"></div><div class="span-3"><label>May the school connect on social media?</label><select id="socialMediaConsent"><option value="false">No preference / not yet</option><option value="true">Yes, I do not mind</option></select></div>');
function syncDialCode(){const c=phonePicker?.getSelectedCountryData?.();if(c?.dialCode)showCountry(c);else phonePreview()}
$('rawPhone').addEventListener('countrychange',syncDialCode);if(phonePicker)syncDialCode();
function options(id,list){$(id).innerHTML='<option value="">Select…</option>'+list.map(x=>`<option>${x}</option>`).join('')};options('volunteerType',types);options('specialty',specs);$('schoolTitle').textContent=`${V.school().name||V.school().id} · Volunteer Register`;
function assertAdmin(){const roles=[localStorage.getItem('role'),localStorage.getItem('somap_role')].map(value=>String(value||'').toLowerCase().replace(/[\s-]/g,'_'));const allowed=['admin','director','headteacher','head_teacher'];if(!roles.some(role=>allowed.includes(role))){document.body.innerHTML='<main class="shell"><div class="notice"><b>Restricted module.</b> Volunteer management requires an Admin, Director, or Headteacher session. <a href="../login.html">Return to sign-in</a>.</div></main>';throw Error('Volunteer administrator role required')}}
function toggleOther(){const t=$('volunteerType').value==='Other',s=$('specialty').value==='Other';$('typeOtherWrap').classList.toggle('hidden',!t);$('specialtyOtherWrap').classList.toggle('hidden',!s);$('volunteerTypeOther').required=t;$('specialtyOther').required=s} $('volunteerType').onchange=toggleOther;$('specialty').onchange=toggleOther;
function days(){const a=new Date($('plannedArrivalDate').value),d=new Date($('plannedDepartureDate').value);$('plannedDaysToStay').value=Number.isFinite(+a)&&Number.isFinite(+d)&&d>=a?Math.floor((d-a)/86400000)+1:''}$('plannedArrivalDate').onchange=days;$('plannedDepartureDate').onchange=days;
function phonePreview(){$('phonePreview').textContent=V.normalizePhone($('rawPhone').value,$('countryCode').value)||'Normalized number appears here'}$('rawPhone').oninput=phonePreview;$('countryCode').onchange=phonePreview;
async function nextId(){const y=V.year(),snap=await V.ref('volunteerCounters',y).transaction(n=>(Number(n)||0)+1);return`VOL-${y}-${String(snap.snapshot.val()).padStart(4,'0')}`}
function val(id){return $(id)?.value?.trim?.()||''}function bool(id){return val(id)==='true'}
const pendingFiles={passportCopy:null,passportPhoto:null};
function renderFilePreview(kind,file,url=''){const box=$(kind+'Preview');if(file){const image=file.type.startsWith('image/')?`<img src="${URL.createObjectURL(file)}" alt="Selected file preview">`:'';box.innerHTML=`${image}<b>${V.escapeHtml(file.name)}</b> · ${(file.size/1048576).toFixed(1)} MB`;return}box.innerHTML=url?`<a href="${V.escapeHtml(url)}" target="_blank" rel="noopener">View current uploaded file</a>`:''}
function bindFileDrop(kind,maxMb){const input=$(kind+'File'),drop=$(kind+'Drop');input.addEventListener('change',()=>{const file=input.files?.[0]||null;if(file&&file.size>maxMb*1048576){input.value='';pendingFiles[kind]=null;alert(`File must be ${maxMb} MB or smaller.`);return}pendingFiles[kind]=file;renderFilePreview(kind,file)});['dragenter','dragover'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.add('dragover')}));['dragleave','drop'].forEach(type=>drop.addEventListener(type,e=>{e.preventDefault();drop.classList.remove('dragover')}));drop.addEventListener('drop',e=>{const file=e.dataTransfer?.files?.[0];if(!file)return;if(file.size>maxMb*1048576){alert(`File must be ${maxMb} MB or smaller.`);return}const allowed=kind==='passportPhoto'?['image/jpeg','image/png'].includes(file.type):['image/jpeg','image/png','application/pdf'].includes(file.type);if(!allowed){alert(kind==='passportPhoto'?'Choose a JPG or PNG image.':'Choose a JPG, PNG, or PDF file.');return}pendingFiles[kind]=file;renderFilePreview(kind,file)})}
bindFileDrop('passportCopy',10);bindFileDrop('passportPhoto',5);
const CLOUDINARY_CLOUD='dg7vnrkgd',CLOUDINARY_PRESET='somap_unsigned',uploadProgress={};
function showUploadProgress(){const parts=Object.entries(uploadProgress).map(([kind,percent])=>`${kind==='passport-copy'?'Passport':'Photo'} ${percent}%`);$('saveMessage').textContent=parts.length?`Uploading to Cloudinary… ${parts.join(' · ')}`:'Uploading files…'}
async function uploadVolunteerFile(file,key,kind){if(!file)return'';const schoolId=String(V.school().id||'school').replace(/[^a-zA-Z0-9_-]/g,'_'),form=new FormData();form.append('file',file);form.append('upload_preset',CLOUDINARY_PRESET);form.append('folder',`somap/volunteers/${schoolId}/${V.year()}/${key}`);uploadProgress[kind]=0;showUploadProgress();return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',`https://api.cloudinary.com/v1_1/${CLOUDINARY_CLOUD}/auto/upload`);xhr.timeout=45000;xhr.upload.onprogress=e=>{if(e.lengthComputable){uploadProgress[kind]=Math.round(e.loaded/e.total*100);showUploadProgress()}};xhr.onload=()=>{try{const data=JSON.parse(xhr.responseText||'{}');if(xhr.status<200||xhr.status>=300||!data.secure_url)throw Error(data?.error?.message||`Upload failed (${xhr.status})`);uploadProgress[kind]=100;showUploadProgress();resolve(data.secure_url)}catch(err){reject(err)}};xhr.onerror=()=>reject(Error('Cloudinary upload failed. Check the internet connection and try again.'));xhr.ontimeout=()=>reject(Error('Cloudinary upload took too long. Check the connection and try again.'));xhr.send(form)})}
$('volunteerForm').onsubmit=async e=>{e.preventDefault();$('saveMessage').textContent='Saving…';Object.keys(uploadProgress).forEach(key=>delete uploadProgress[key]);try{const selectedCountry=selectTypedCountry();if(!selectedCountry)throw Error('Choose a country from the list so its calling code can be set.');const normalizedPhone=V.normalizePhone(val('rawPhone'),val('countryCode'));if(!normalizedPhone)throw Error('A valid phone number is required.');const key=val('editKey')||V.ref('volunteers').push().key,existing=records[key]||{},id=val('volunteerId')||await nextId(),displayName=[val('firstName'),val('middleName'),val('lastName'),val('otherName')].filter(Boolean).join(' ');if(pendingFiles.passportCopy||pendingFiles.passportPhoto)$('saveMessage').textContent='Uploading files…';const [passportCopyUrl,passportPhotoUrl]=await Promise.all([pendingFiles.passportCopy?uploadVolunteerFile(pendingFiles.passportCopy,key,'passport-copy'):existing.passportCopyUrl||'',pendingFiles.passportPhoto?uploadVolunteerFile(pendingFiles.passportPhoto,key,'passport-photo'):existing.passportPhotoUrl||'']);const now=firebase.database.ServerValue.TIMESTAMP;const data={...existing,volunteerId:id,displayName,normalizedNameTokens:V.nameTokens(displayName),normalizedPhone,rawPhone:val('rawPhone'),passportCopyUrl,passportPhotoUrl,plannedDaysToStay:Number(val('plannedDaysToStay'))||0,isStudent:bool('isStudent'),accessEnabled:bool('accessEnabled'),archiveAccessAllowed:bool('archiveAccessAllowed'),accessLevel:Number(val('accessLevel')||1),schoolId:V.school().id,schoolName:V.school().name||V.school().id,year:V.year(),updatedAt:now,createdAt:existing.createdAt||now,createdBy:firebase.auth().currentUser?.email||localStorage.getItem('role')||'admin'};fields.forEach(f=>{if(!['rawPhone','accessEnabled','accessLevel','archiveAccessAllowed'].includes(f))data[f]=val(f)});$('saveMessage').textContent='Saving volunteer details…';await V.ref(`volunteers/${key}`).set(data);$('saveMessage').textContent='Volunteer record saved.';reset();await load()}catch(err){console.error('Volunteer save failed',err);$('saveMessage').textContent=err.message}}
function reset(){$('volunteerForm').reset();$('editKey').value='';$('volunteerId').value='';$('countryCode').value='+255';$('countryStatus').classList.add('hidden');$('countryStatus').textContent='';pendingFiles.passportCopy=null;pendingFiles.passportPhoto=null;renderFilePreview('passportCopy',null);renderFilePreview('passportPhoto',null);phonePicker?.setSelectedCountry?.('tz');$('accessEnabled').value='true';toggleOther();phonePreview();days()}$('resetForm').onclick=reset;
function statusBadge(v){return`<span class="badge ${v==='suspended'?'danger':v==='expected'?'warn':''}">${V.escapeHtml(v||'—')}</span>`}
function filtered(){const q=V.normalizeName($('search').value);return Object.entries(records).filter(([,v])=>(!currentFilter||v.status===currentFilter)&&(!q||V.normalizeName([v.displayName,v.country,v.normalizedPhone,v.specialty].join(' ')).includes(q)))}
function render(){const list=filtered();$('volunteerRows').innerHTML=list.length?list.map(([k,v])=>`<tr><td><img class="avatar" src="${V.escapeHtml(v.passportPhotoUrl||'../images/somap-logo.png')}" alt=""></td><td><b>${V.escapeHtml(v.displayName)}</b><br><small>${V.escapeHtml(v.volunteerId)}</small></td><td>${V.escapeHtml(v.country)}</td><td>${V.escapeHtml(v.normalizedPhone)}</td><td>${V.escapeHtml(v.volunteerType)}</td><td>${V.escapeHtml(v.specialty)}</td><td>${V.escapeHtml(v.plannedArrivalDate)}</td><td>${V.escapeHtml(v.plannedDepartureDate)}</td><td>${statusBadge(v.status)}</td><td>${v.accessEnabled?'Enabled':'Disabled'}</td><td><button class="btn secondary" data-edit="${k}">Edit</button> <button class="btn secondary" data-toggle="${k}">${v.accessEnabled?'Disable':'Enable'}</button> <button class="btn secondary" data-archive="${k}">Archive</button></td></tr>`).join(''):'<tr><td colspan="11" class="empty">No volunteer records in this view.</td></tr>';summaries();bindRows()}
function summaries(){const all=Object.values(records),count=x=>all.filter(v=>v.status===x).length,up=all.filter(v=>v.status==='expected'&&v.plannedArrivalDate&&new Date(v.plannedArrivalDate)>=new Date(new Date().toDateString())).length;$('sTotal').textContent=all.length;$('sActive').textContent=count('active');$('sExpected').textContent=count('expected');$('sPast').textContent=count('past');$('sCountries').textContent=new Set(all.map(v=>v.country).filter(Boolean)).size;$('sUpcoming').textContent=up;const group=k=>all.reduce((a,v)=>(a[v[k]||'Not specified']=(a[v[k]||'Not specified']||0)+1,a),{});$('countrySummary').innerHTML=Object.entries(group('country')).map(([k,n])=>`<span class="badge">${V.escapeHtml(k)} · ${n}</span>`).join('');$('specialtySummary').innerHTML=Object.entries(group('specialty')).map(([k,n])=>`<span class="badge">${V.escapeHtml(k)} · ${n}</span>`).join('');$('documentSummary').innerHTML=all.map(v=>`<p><b>${V.escapeHtml(v.displayName)}</b> · ${v.passportCopyUrl?`<a href="${V.escapeHtml(v.passportCopyUrl)}" target="_blank" rel="noopener">Passport copy</a>`:'No passport copy'} · ${v.passportPhotoUrl?'Photo recorded':'No photo'}</p>`).join('')||'<div class="empty">No documents recorded.</div>'}
function bindRows(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{const v=records[b.dataset.toggle];await V.ref(`volunteers/${b.dataset.toggle}`).update({accessEnabled:!v.accessEnabled,updatedAt:firebase.database.ServerValue.TIMESTAMP});load()});document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=async()=>{if(confirm('Archive this volunteer record?')){await V.ref(`volunteers/${b.dataset.archive}`).update({status:'past',accessEnabled:false,archived:true,updatedAt:firebase.database.ServerValue.TIMESTAMP});load()}})}
function edit(k){const v=records[k];$('editKey').value=k;$('volunteerId').value=v.volunteerId||'';fields.forEach(f=>{if($(f)&&v[f]!=null)$(f).value=String(v[f])});pendingFiles.passportCopy=null;pendingFiles.passportPhoto=null;renderFilePreview('passportCopy',null,v.passportCopyUrl);renderFilePreview('passportPhoto',null,v.passportPhotoUrl);if(v.normalizedPhone)phonePicker?.setNumber?.(v.normalizedPhone);selectTypedCountry();$('plannedDaysToStay').value=v.plannedDaysToStay||'';$('isStudent').value=String(!!v.isStudent);toggleOther();phonePreview();show('register');scrollTo({top:0,behavior:'smooth'})}
function show(name){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$(`panel-${name}`).classList.add('active');document.querySelector(`[data-tab="${name}"]`)?.classList.add('active')}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter||'';show(b.dataset.tab||'list');b.classList.add('active');render()});$('search').oninput=render;
async function logs(){const s=await V.ref('volunteerAccessLogs').once('value'),a=[];s.forEach(c=>a.push(c.val()));a.sort((x,y)=>(y.timestamp||0)-(x.timestamp||0));$('logRows').innerHTML=a.slice(0,200).map(x=>`<tr><td>${x.timestamp?new Date(x.timestamp).toLocaleString():'—'}</td><td>${V.escapeHtml(x.enteredNames)}</td><td>${V.escapeHtml(x.normalizedPhone)}</td><td>${V.escapeHtml(x.matchedVolunteerId)}</td><td>${x.success?'Success':'Failed'}</td><td>${V.escapeHtml(x.failureReason)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No access logs.</td></tr>'}
async function load(){const s=await V.ref('volunteers').once('value');records=s.val()||{};render();logs()}window.addEventListener('somapYearChanged',load);assertAdmin();phonePreview();load().catch(e=>$('saveMessage').textContent=e.message);
})();
