(async function(){
  'use strict';
  const V=SomapVolunteers,s=V.requireSession(),$=id=>document.getElementById(id);
  const CONTACT='+255 686 828 732';
  let volunteer=null,volunteerKey='',profile={},certificate=null;
  const archiveMode=new URLSearchParams(location.search).get('archive')==='1';
  const autoCountKey=`somap.volunteerWelcomeAutoCount.${s.schoolId}.${s.year}.${s.volunteerId}`;
  function clean(value,fallback=''){return String(value||fallback).replace(/\s+/g,' ').trim()}
  function mission(v){return clean([v.visitPurpose,v.plannedActivities,v.specialty&&`Specialty: ${v.specialty}`,v.skills&&`Skills: ${v.skills}`,v.childBenefit].filter(Boolean).join('. '),'To share time, knowledge, and care with our school community.')}
  function date(value){return value?new Date(value+'T12:00:00').toLocaleDateString(undefined,{dateStyle:'long'}):''}
  async function imageData(url){if(!url)return null;try{const response=await fetch(url,{mode:'cors'});if(!response.ok)throw Error('Image unavailable');const blob=await response.blob();return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob)})}catch(_){return null}}
  async function firstImage(...urls){for(const url of urls){const data=await imageData(url);if(data)return data}return null}
  function writeWrapped(doc,text,x,y,width,lineHeight,maxLines){const lines=doc.splitTextToSize(clean(text),width).slice(0,maxLines);doc.text(lines,x,y,{align:'center'});return y+lines.length*lineHeight}
  async function createCertificate(){
    if(certificate)return certificate;
    if(!window.jspdf?.jsPDF)throw Error('The PDF generator did not load. Please use the download button to try again.');
    const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),school=clean(s.schoolName||V.school().name,'Our School');
    const [schoolLogo,volunteerPhoto,somapLogo]=await Promise.all([firstImage(profile.logoUrl,V.school().logoUrl,'../images/somap-logo.png'),firstImage(volunteer.passportPhotoUrl,'../images/somap-logo.png'),firstImage('../images/somap-logo.png')]);
    doc.setFillColor(253,251,244);doc.rect(0,0,297,210,'F');doc.setDrawColor(23,107,77);doc.setLineWidth(2);doc.rect(7,7,283,196);doc.setDrawColor(208,163,61);doc.setLineWidth(.7);doc.rect(11,11,275,188);
    if(somapLogo){try{doc.saveGraphicsState();doc.setGState(new doc.GState({opacity:.045}));doc.addImage(somapLogo,'PNG',93,30,110,110,undefined,'FAST');doc.restoreGraphicsState()}catch(_){}}
    if(schoolLogo)doc.addImage(schoolLogo,schoolLogo.includes('image/png')?'PNG':'JPEG',20,18,27,27,undefined,'FAST');
    if(volunteerPhoto){doc.setDrawColor(208,163,61);doc.setLineWidth(1.2);doc.circle(252,31.5,17.5,'S');doc.addImage(volunteerPhoto,volunteerPhoto.includes('image/png')?'PNG':'JPEG',236,15.5,32,32,undefined,'FAST')}
    doc.setTextColor(155,118,38);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('VOLUNTEER WELCOME CERTIFICATE',148.5,22,{align:'center'});
    doc.setTextColor(21,79,60);doc.setFont('times','bold');doc.setFontSize(28);doc.text(`Welcome to ${school}`,148.5,39,{align:'center'});
    doc.setTextColor(80,91,85);doc.setFont('times','normal');doc.setFontSize(12);doc.text('With gratitude and great pleasure, we welcome',148.5,54,{align:'center'});
    doc.setTextColor(155,118,38);doc.setFont('times','bolditalic');doc.setFontSize(25);doc.text(clean(volunteer.displayName,'Our Volunteer'),148.5,68,{align:'center'});
    doc.setTextColor(55,70,63);doc.setFont('helvetica','normal');doc.setFontSize(10.5);let y=80;
    y=writeWrapped(doc,'Your presence, knowledge, and service enrich our school community. We value the time and purpose you have chosen to share with our children and team.',148.5,y,205,5,3)+3;
    doc.setTextColor(23,107,77);doc.setFont('helvetica','bold');doc.text('YOUR MISSION WITH US',148.5,y,{align:'center'});y+=7;doc.setTextColor(55,70,63);doc.setFont('helvetica','normal');y=writeWrapped(doc,mission(volunteer),148.5,y,205,5,4)+3;
    const history=clean(profile.schoolHistory||profile.history,`${school} is committed to learning, dignity, service, and creating opportunities for every child.`);doc.setTextColor(23,107,77);doc.setFont('helvetica','bold');doc.text('OUR SCHOOL STORY',148.5,y,{align:'center'});y+=7;doc.setTextColor(55,70,63);doc.setFont('helvetica','normal');writeWrapped(doc,history,148.5,y,205,5,4);
    doc.setFillColor(237,246,240);doc.roundedRect(55,166,187,15,3,3,'F');doc.setTextColor(23,75,57);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(`Information and assistance · WhatsApp ${CONTACT}`,148.5,175.5,{align:'center'});
    doc.setTextColor(155,118,38);doc.setFont('times','bolditalic');doc.setFontSize(13);doc.text('We value you. Welcome to our school family.',148.5,190,{align:'center'});
    doc.setTextColor(95,105,100);doc.setFont('helvetica','normal');doc.setFontSize(8);doc.text([date(volunteer.plannedArrivalDate),volunteer.volunteerId].filter(Boolean).join(' · '),148.5,197,{align:'center'});
    certificate=doc;return doc;
  }
  async function downloadAppreciation(){const button=$('downloadAppreciation');button.disabled=true;try{if(!window.jspdf?.jsPDF)throw Error('The PDF generator did not load.');const {jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'}),school=clean(s.schoolName||V.school().name,'Our School'),name=clean(volunteer.displayName,'Our Volunteer');doc.setFillColor(253,251,244);doc.rect(0,0,297,210,'F');doc.setDrawColor(23,107,77);doc.setLineWidth(2);doc.rect(7,7,283,196);doc.setDrawColor(208,163,61);doc.setLineWidth(.7);doc.rect(11,11,275,188);doc.setTextColor(155,118,38);doc.setFont('helvetica','bold');doc.setFontSize(11);doc.text('CERTIFICATE OF VOLUNTEER APPRECIATION',148.5,34,{align:'center'});doc.setTextColor(21,79,60);doc.setFont('times','bold');doc.setFontSize(29);doc.text('With sincere gratitude',148.5,55,{align:'center'});doc.setTextColor(70);doc.setFont('times','normal');doc.setFontSize(13);doc.text('This certificate is proudly presented to',148.5,72,{align:'center'});doc.setTextColor(155,118,38);doc.setFont('times','bolditalic');doc.setFontSize(27);doc.text(name,148.5,90,{align:'center'});doc.setTextColor(55,70,63);doc.setFont('helvetica','normal');doc.setFontSize(11);writeWrapped(doc,`In appreciation of your time, knowledge, service, and meaningful contribution to the children and community of ${school}. Your work has become part of our school story, and we thank you for serving with purpose and care.`,148.5,108,205,6,5);doc.setTextColor(23,107,77);doc.setFont('times','bold');doc.setFontSize(19);doc.text(school,148.5,151,{align:'center'});doc.setTextColor(95);doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text(`Program completed ${date(volunteer.plannedDepartureDate)||new Date().toLocaleDateString()} · Academic year ${s.year}`,148.5,164,{align:'center'});doc.setTextColor(155,118,38);doc.setFont('times','bolditalic');doc.setFontSize(14);doc.text('Thank you for making a difference.',148.5,184,{align:'center'});doc.save(`Appreciation-${name.replace(/[^a-z0-9]+/gi,'-')}-${s.year}.pdf`);$('appreciationStatus').textContent='Your end-of-program appreciation certificate has been downloaded.';$('appreciationStatus').classList.remove('hidden')}catch(err){$('appreciationStatus').textContent=err.message;$('appreciationStatus').classList.remove('hidden')}finally{button.disabled=false}}
  async function reserveAutomaticDownload(){let local=Number(localStorage.getItem(autoCountKey)||0);if(local>=2)return false;if(volunteerKey){try{let allowed=false;const counter=V.ref(`volunteers/${volunteerKey}/certificateArchive/welcome/automaticDownloads`,s.year);const result=await counter.transaction(current=>{const count=Number(current||0);if(count>=2)return;allowed=true;return count+1});if(!result.committed)return false;localStorage.setItem(autoCountKey,String(Number(result.snapshot.val())||local+1));return allowed}catch(err){console.warn('Certificate download counter used local fallback:',err.message)}}local++;localStorage.setItem(autoCountKey,String(local));return true}
  async function download(options={}){const automatic=options.automatic===true,button=$('downloadCertificate');if(automatic&&!await reserveAutomaticDownload()){location.replace('volunteerportal.html');return}button.disabled=true;$('downloadStatus').textContent='Creating your personalized certificate…';try{const doc=await createCertificate(),name=clean(volunteer.displayName,'volunteer').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'');doc.save(`Welcome-${name}-${s.year}.pdf`);$('downloadHeading').textContent='Welcome certificate ready';$('downloadStatus').textContent=archiveMode?'Your archived welcome certificate has been downloaded.':'Your certificate has been downloaded. Future automatic downloads stop after the second welcome; it remains available in your archive.';sessionStorage.setItem('somap.volunteerWelcomeDownloaded',`${s.volunteerId}:${s.year}`);if(!archiveMode)startRedirect()}catch(err){$('downloadHeading').textContent='Your welcome certificate is ready to retry';$('downloadStatus').textContent=err.message}finally{button.disabled=false}}
  function startRedirect(){let seconds=7;const tick=()=>{$('redirectStatus').textContent=`Opening your volunteer dashboard in ${seconds} second${seconds===1?'':'s'}…`;if(seconds--<=0)location.replace('volunteerportal.html');else setTimeout(tick,1000)};tick()}
  try{
    const base=path=>firebase.database().ref(window.SOMAP?.P?SOMAP.P(path):path),[all,profileSnap]=await Promise.all([V.ref('volunteers',s.year).once('value'),base('profile').once('value').catch(()=>null)]);
    all.forEach(child=>{const value=child.val();if(value?.volunteerId===s.volunteerId){volunteer=value;volunteerKey=child.key}});if(!volunteer)throw Error('Your volunteer record could not be loaded.');profile=profileSnap?.val()||{};
    const school=clean(s.schoolName||V.school().name,'Our School');$('schoolName').textContent=school;$('volunteerName').textContent=clean(volunteer.displayName,'Volunteer');$('volunteerPhoto').src=volunteer.passportPhotoUrl||'../images/somap-logo.png';$('schoolLogo').src=profile.logoUrl||V.school().logoUrl||'../images/somap-logo.png';$('volunteerMeta').textContent=[volunteer.country,volunteer.specialty,date(volunteer.plannedArrivalDate)].filter(Boolean).join(' · ');$('missionText').textContent=mission(volunteer);$('schoolHistory').textContent=clean(profile.schoolHistory||profile.history,`${school} is committed to learning, dignity, service, and creating opportunities for every child.`);
    $('downloadCertificate').onclick=()=>download({automatic:false});
    if(archiveMode){$('downloadHeading').textContent='Certificate archive';$('downloadStatus').textContent='Download your welcome certificate whenever you need it. This manual archive download is not limited.';$('downloadAppreciation').classList.remove('hidden');const ended=volunteer.status==='completed'||(volunteer.plannedDepartureDate&&new Date(volunteer.plannedDepartureDate+'T23:59:59')<new Date());if(!ended){$('downloadAppreciation').disabled=true;$('appreciationStatus').textContent='Your end-of-program appreciation certificate will become available automatically when your visit is completed.';$('appreciationStatus').classList.remove('hidden')}else{$('downloadAppreciation').onclick=downloadAppreciation}}else{const marker=`${s.volunteerId}:${s.year}`;if(sessionStorage.getItem('somap.volunteerWelcomeDownloaded')===marker)startRedirect();else setTimeout(()=>download({automatic:true}),700)}
  }catch(err){$('downloadHeading').textContent='Unable to prepare the welcome certificate';$('downloadStatus').textContent=err.message;$('downloadCertificate').disabled=true}
})();
