(function(){'use strict';const V=SomapVolunteers;let records={};let currentFilter='';const $=id=>document.getElementById(id);const fields=['firstName','middleName','lastName','otherName','gender','dateOfBirth','country','passportNumber','organization','passportCopyUrl','passportPhotoUrl','countryCode','rawPhone','email','emergencyContact','volunteerType','volunteerTypeOther','specialty','specialtyOther','professionOrStudentStatus','institution','course','studentLevel','skills','strengths','childBenefit','languages','previousExperience','notes','plannedArrivalDate','plannedDepartureDate','actualArrivalDate','actualDepartureDate','status','assignedContact','accommodationNotes','visitPurpose','plannedActivities','introductionLetterUrl','organizationLetterUrl','agreementUrl','accessEnabled','accessLevel','archiveAccessAllowed','accessExpiresAt'];
const phoneCss=document.createElement('link');phoneCss.rel='stylesheet';phoneCss.href='https://cdn.jsdelivr.net/npm/intl-tel-input@28.0.0/build/css/intlTelInput.css';document.head.appendChild(phoneCss);
const types=['Current volunteer','Expected volunteer','Past volunteer','Exchange visitor','Student volunteer','Professional volunteer','Project volunteer','Sponsorship-linked volunteer','Organization partner','Short-term visitor','Long-term volunteer','Other'];const specs=['Teaching support','English reading','Mathematics support','Science support','Computer/ICT','Coding/technology','Sports/games','Music','Arts/drawing','Counselling/mentorship','Library/reading','Health/first aid','Construction/project support','Photography/media','Administration','Fundraising coordination','Child sponsorship support','Cultural exchange','Environment/gardening','Other'];
const phonePicker=window.intlTelInput?window.intlTelInput($('rawPhone'),{initialCountry:'tz',countrySearch:true,separateDialCode:true,preferredCountries:['tz','ke','ug','rw','za','gb','de','us']}):null;
function syncDialCode(){const c=phonePicker?.getSelectedCountryData?.();if(c?.dialCode)$('countryCode').value=`+${c.dialCode}`;phonePreview()}
$('rawPhone').addEventListener('countrychange',syncDialCode);if(phonePicker){$('countryCode').closest('div').style.display='none';const phoneField=$('rawPhone').closest('div');phoneField.classList.remove('span-3');phoneField.classList.add('span-6');phoneField.querySelector('label').textContent='Country & Phone / WhatsApp *';$('phonePreview').insertAdjacentText('beforebegin','Select a flag or search any country by name or calling code. ');syncDialCode()}
function options(id,list){$(id).innerHTML='<option value="">Select…</option>'+list.map(x=>`<option>${x}</option>`).join('')};options('volunteerType',types);options('specialty',specs);$('schoolTitle').textContent=`${V.school().name||V.school().id} · Volunteer Register`;
function assertAdmin(){const role=String(localStorage.getItem('role')||'').toLowerCase().replace(/[\s-]/g,'_');const allowed=['admin','director','headteacher','head_teacher'];if(!allowed.includes(role)){document.body.innerHTML='<main class="shell"><div class="notice"><b>Restricted module.</b> Volunteer management requires an Admin, Director, or Headteacher session. <a href="../login.html">Return to sign-in</a>.</div></main>';throw Error('Volunteer administrator role required')}}
function toggleOther(){const t=$('volunteerType').value==='Other',s=$('specialty').value==='Other';$('typeOtherWrap').classList.toggle('hidden',!t);$('specialtyOtherWrap').classList.toggle('hidden',!s);$('volunteerTypeOther').required=t;$('specialtyOther').required=s} $('volunteerType').onchange=toggleOther;$('specialty').onchange=toggleOther;
function days(){const a=new Date($('plannedArrivalDate').value),d=new Date($('plannedDepartureDate').value);$('plannedDaysToStay').value=Number.isFinite(+a)&&Number.isFinite(+d)&&d>=a?Math.floor((d-a)/86400000)+1:''}$('plannedArrivalDate').onchange=days;$('plannedDepartureDate').onchange=days;
function phonePreview(){$('phonePreview').textContent=V.normalizePhone($('rawPhone').value,$('countryCode').value)||'Normalized number appears here'}$('rawPhone').oninput=phonePreview;$('countryCode').onchange=phonePreview;
async function nextId(){const y=V.year(),snap=await V.ref('volunteerCounters',y).transaction(n=>(Number(n)||0)+1);return`VOL-${y}-${String(snap.snapshot.val()).padStart(4,'0')}`}
function val(id){return $(id)?.value?.trim?.()||''}function bool(id){return val(id)==='true'}
$('volunteerForm').onsubmit=async e=>{e.preventDefault();$('saveMessage').textContent='Saving…';try{const now=firebase.database.ServerValue.TIMESTAMP,key=val('editKey')||V.ref('volunteers').push().key,id=val('volunteerId')||await nextId(),existing=records[key]||{},displayName=[val('firstName'),val('middleName'),val('lastName'),val('otherName')].filter(Boolean).join(' '),normalizedPhone=V.normalizePhone(val('rawPhone'),val('countryCode'));if(!normalizedPhone)throw Error('A valid phone number is required.');const data={...existing,volunteerId:id,displayName,normalizedNameTokens:V.nameTokens(displayName),normalizedPhone,rawPhone:val('rawPhone'),plannedDaysToStay:Number(val('plannedDaysToStay'))||0,isStudent:bool('isStudent'),accessEnabled:bool('accessEnabled'),archiveAccessAllowed:bool('archiveAccessAllowed'),accessLevel:Number(val('accessLevel')||1),schoolId:V.school().id,schoolName:V.school().name||V.school().id,year:V.year(),updatedAt:now,createdAt:existing.createdAt||now,createdBy:firebase.auth().currentUser?.email||localStorage.getItem('role')||'admin'};fields.forEach(f=>{if(!['rawPhone','accessEnabled','accessLevel','archiveAccessAllowed'].includes(f))data[f]=val(f)});await V.ref(`volunteers/${key}`).set(data);$('saveMessage').textContent='Volunteer record saved.';reset();await load()}catch(err){$('saveMessage').textContent=err.message}}
function reset(){$('volunteerForm').reset();$('editKey').value='';$('volunteerId').value='';$('countryCode').value='+255';phonePicker?.setSelectedCountry?.('tz');$('accessEnabled').value='true';toggleOther();phonePreview();days()}$('resetForm').onclick=reset;
function statusBadge(v){return`<span class="badge ${v==='suspended'?'danger':v==='expected'?'warn':''}">${V.escapeHtml(v||'—')}</span>`}
function filtered(){const q=V.normalizeName($('search').value);return Object.entries(records).filter(([,v])=>(!currentFilter||v.status===currentFilter)&&(!q||V.normalizeName([v.displayName,v.country,v.normalizedPhone,v.specialty].join(' ')).includes(q)))}
function render(){const list=filtered();$('volunteerRows').innerHTML=list.length?list.map(([k,v])=>`<tr><td><img class="avatar" src="${V.escapeHtml(v.passportPhotoUrl||'../images/somap-logo.png')}" alt=""></td><td><b>${V.escapeHtml(v.displayName)}</b><br><small>${V.escapeHtml(v.volunteerId)}</small></td><td>${V.escapeHtml(v.country)}</td><td>${V.escapeHtml(v.normalizedPhone)}</td><td>${V.escapeHtml(v.volunteerType)}</td><td>${V.escapeHtml(v.specialty)}</td><td>${V.escapeHtml(v.plannedArrivalDate)}</td><td>${V.escapeHtml(v.plannedDepartureDate)}</td><td>${statusBadge(v.status)}</td><td>${v.accessEnabled?'Enabled':'Disabled'}</td><td><button class="btn secondary" data-edit="${k}">Edit</button> <button class="btn secondary" data-toggle="${k}">${v.accessEnabled?'Disable':'Enable'}</button> <button class="btn secondary" data-archive="${k}">Archive</button></td></tr>`).join(''):'<tr><td colspan="11" class="empty">No volunteer records in this view.</td></tr>';summaries();bindRows()}
function summaries(){const all=Object.values(records),count=x=>all.filter(v=>v.status===x).length,up=all.filter(v=>v.status==='expected'&&v.plannedArrivalDate&&new Date(v.plannedArrivalDate)>=new Date(new Date().toDateString())).length;$('sTotal').textContent=all.length;$('sActive').textContent=count('active');$('sExpected').textContent=count('expected');$('sPast').textContent=count('past');$('sCountries').textContent=new Set(all.map(v=>v.country).filter(Boolean)).size;$('sUpcoming').textContent=up;const group=k=>all.reduce((a,v)=>(a[v[k]||'Not specified']=(a[v[k]||'Not specified']||0)+1,a),{});$('countrySummary').innerHTML=Object.entries(group('country')).map(([k,n])=>`<span class="badge">${V.escapeHtml(k)} · ${n}</span>`).join('');$('specialtySummary').innerHTML=Object.entries(group('specialty')).map(([k,n])=>`<span class="badge">${V.escapeHtml(k)} · ${n}</span>`).join('');$('documentSummary').innerHTML=all.map(v=>`<p><b>${V.escapeHtml(v.displayName)}</b> · ${v.passportCopyUrl?`<a href="${V.escapeHtml(v.passportCopyUrl)}" target="_blank" rel="noopener">Passport copy</a>`:'No passport copy'} · ${v.passportPhotoUrl?'Photo recorded':'No photo'}</p>`).join('')||'<div class="empty">No documents recorded.</div>'}
function bindRows(){document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>edit(b.dataset.edit));document.querySelectorAll('[data-toggle]').forEach(b=>b.onclick=async()=>{const v=records[b.dataset.toggle];await V.ref(`volunteers/${b.dataset.toggle}`).update({accessEnabled:!v.accessEnabled,updatedAt:firebase.database.ServerValue.TIMESTAMP});load()});document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=async()=>{if(confirm('Archive this volunteer record?')){await V.ref(`volunteers/${b.dataset.archive}`).update({status:'past',accessEnabled:false,archived:true,updatedAt:firebase.database.ServerValue.TIMESTAMP});load()}})}
function edit(k){const v=records[k];$('editKey').value=k;$('volunteerId').value=v.volunteerId||'';fields.forEach(f=>{if($(f)&&v[f]!=null)$(f).value=String(v[f])});if(v.normalizedPhone)phonePicker?.setNumber?.(v.normalizedPhone);$('plannedDaysToStay').value=v.plannedDaysToStay||'';$('isStudent').value=String(!!v.isStudent);toggleOther();phonePreview();show('register');scrollTo({top:0,behavior:'smooth'})}
function show(name){document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));$(`panel-${name}`).classList.add('active');document.querySelector(`[data-tab="${name}"]`)?.classList.add('active')}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{currentFilter=b.dataset.filter||'';show(b.dataset.tab||'list');b.classList.add('active');render()});$('search').oninput=render;
async function logs(){const s=await V.ref('volunteerAccessLogs').once('value'),a=[];s.forEach(c=>a.push(c.val()));a.sort((x,y)=>(y.timestamp||0)-(x.timestamp||0));$('logRows').innerHTML=a.slice(0,200).map(x=>`<tr><td>${x.timestamp?new Date(x.timestamp).toLocaleString():'—'}</td><td>${V.escapeHtml(x.enteredNames)}</td><td>${V.escapeHtml(x.normalizedPhone)}</td><td>${V.escapeHtml(x.matchedVolunteerId)}</td><td>${x.success?'Success':'Failed'}</td><td>${V.escapeHtml(x.failureReason)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No access logs.</td></tr>'}
async function load(){const s=await V.ref('volunteers').once('value');records=s.val()||{};render();logs()}window.addEventListener('somapYearChanged',load);assertAdmin();phonePreview();load().catch(e=>$('saveMessage').textContent=e.message);
})();
