(function (global) {
  "use strict";

  function money(value) {
    return global.SomapBankAuditEngine.formatTsh(value);
  }

  async function imageData(urls) {
    for (const url of urls) {
      try {
        const blob = await fetch(url).then((r) => {
          if (!r.ok) throw new Error("Image failed");
          return r.blob();
        });
        return await new Promise((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = () => resolve(reader.result);
          reader.onerror = reject;
          reader.readAsDataURL(blob);
        });
      } catch (_) {}
    }
    return null;
  }

  function addHeader(doc, audit, logo, title) {
    const w = doc.internal.pageSize.getWidth();
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, w, 58, "F");
    if (logo) doc.addImage(logo, "PNG", 36, 12, 34, 34);
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.text(title || "SoMAp Bank Audit & Analyzer Report", logo ? 82 : 36, 32);
    doc.setFontSize(9);
    doc.text(`${audit.schoolName || "School"} | ${audit.bankName || "Bank statement"} | ${audit.year || ""}`, logo ? 82 : 36, 46);
    doc.setTextColor(15, 23, 42);
  }

  function section(doc, text, y) {
    doc.setFontSize(13);
    doc.setTextColor(15, 23, 42);
    doc.text(text, 36, y);
    doc.setDrawColor(226, 232, 240);
    doc.line(36, y + 6, 806, y + 6);
    return y + 18;
  }

  function table(doc, y, head, body) {
    doc.autoTable({
      startY: y,
      head: [head],
      body,
      margin: { left: 36, right: 36 },
      styles: { fontSize: 7, cellPadding: 3, overflow: "linebreak" },
      headStyles: { fillColor: [30, 64, 175], textColor: [255, 255, 255] },
      alternateRowStyles: { fillColor: [248, 250, 252] }
    });
    return doc.lastAutoTable.finalY + 16;
  }

  async function download(audit) {
    if (!global.jspdf?.jsPDF) throw new Error("PDF library missing.");
    const doc = new global.jspdf.jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
    const logo = await imageData([audit.schoolLogoUrl, "../images/somap-logo.png.jpg", "../images/somap-logo.png"].filter(Boolean));
    addHeader(doc, audit, logo);
    let y = 92;
    doc.setFontSize(18);
    doc.text("Company Financial Accountability Report", 36, y);
    y += 22;
    doc.setFontSize(10);
    const intro = "This report supports company financial visibility, reconciliation, and evidence-based review. The same rules are applied to all transactions, account operators, employees, directors, recipients, and bank statement entries.";
    doc.text(doc.splitTextToSize(intro, 760), 36, y);
    y += 42;
    y = table(doc, y, ["Metric", "Value"], [
      ["Statement file", audit.uploadedFileName || ""],
      ["Statement period", `${audit.statementPeriodFrom || "Not set"} to ${audit.statementPeriodTo || "Not set"}`],
      ["Generated", new Date().toLocaleString()],
      ["Generated by", audit.uploadedBy?.email || ""]
    ]);

    doc.addPage();
    addHeader(doc, audit, logo, "Executive Summary");
    y = 82;
    y = table(doc, y, ["Metric", "Amount / Count"], [
      ["Total deposits", money(audit.totals?.totalDeposits)],
      ["Total withdrawals", money(audit.totals?.totalWithdrawals)],
      ["Net movement", money(audit.totals?.netMovement)],
      ["Opening balance", money(audit.totals?.openingBalance)],
      ["Closing balance", money(audit.totals?.closingBalance)],
      ["Recalculated closing balance", money(audit.totals?.recalculatedClosingBalance)],
      ["Running balance variance", money(audit.totals?.balanceVariance)],
      ["Review items", String(audit.totals?.reviewItems || 0)]
    ]);
    y = section(doc, "Key Findings", y);
    (audit.findings || []).forEach((f) => {
      const lines = doc.splitTextToSize(`- ${f}`, 760);
      doc.text(lines, 40, y);
      y += lines.length * 10 + 5;
    });

    const categories = Object.entries(audit.categoryTotals || {}).map(([name, amount]) => [name, money(amount)]);
    doc.addPage();
    addHeader(doc, audit, logo, "Category Summary");
    y = table(doc, 82, ["Category", "Total"], categories.length ? categories : [["No category totals", ""]]);

    const addTxnSection = (title, rows) => {
      doc.addPage();
      addHeader(doc, audit, logo, title);
      return table(doc, 82, ["Date", "Day", "Category", "Name/Purpose", "Money in", "Money out", "Narration", "Review"], rows.map((t) => [
        t.dateLabel || t.date,
        t.dayOfWeek || "",
        t.category || "",
        t.detectedStudentName || t.detectedPurpose || "",
        t.moneyIn ? money(t.moneyIn) : "",
        t.moneyOut ? money(t.moneyOut) : "",
        t.description || "",
        (t.reviewFlags || []).join("; ")
      ]));
    };

    const txns = audit.transactions || [];
    addTxnSection("Deposits Summary", txns.filter((t) => t.moneyIn > 0));
    addTxnSection("Withdrawals Summary", txns.filter((t) => t.moneyOut > 0));
    addTxnSection("Remedial Collection Analysis", txns.filter((t) => t.category === "Remedial"));
    addTxnSection("Graduation Collection Analysis", txns.filter((t) => t.category === "Graduation"));
    addTxnSection("Transport / Usafiri Collection Analysis", txns.filter((t) => t.category === "Transport / Usafiri"));
    addTxnSection("Unclassified Income Register", txns.filter((t) => t.category === "Unknown income"));
    addTxnSection("Weekend Withdrawal Register", txns.filter((t) => (t.reviewFlags || []).some((flag) => flag.includes("Weekend withdrawal"))));
    addTxnSection("Bank Charges Summary", txns.filter((t) => t.category === "Bank charge" || (t.reviewFlags || []).some((flag) => flag.includes("Bank charge"))));

    doc.addPage();
    addHeader(doc, audit, logo, "Running Balance Reconciliation");
    y = table(doc, 82, ["Check", "Value"], [
      ["Opening balance", money(audit.totals?.openingBalance)],
      ["Total deposits", money(audit.totals?.totalDeposits)],
      ["Total withdrawals", money(audit.totals?.totalWithdrawals)],
      ["Net movement", money(audit.totals?.netMovement)],
      ["Statement closing balance", money(audit.totals?.closingBalance)],
      ["Recalculated closing balance", money(audit.totals?.recalculatedClosingBalance)],
      ["Variance requiring review", money(audit.totals?.balanceVariance)]
    ]);

    addTxnSection("Student / Payment Trace", txns.filter((t) => t.detectedStudentName));
    addTxnSection("Review Items and Evidence Required", audit.reviewItems || []);
    doc.addPage();
    addHeader(doc, audit, logo, "Governance Recommendations");
    y = 88;
    [
      "Attach fuel, repair, service, transfer, and operational evidence to withdrawal events where available.",
      "Classify unclear incoming payments after confirming the student name and payment purpose.",
      "Review weekend withdrawals using the same company rule for every account operator and recipient.",
      "Compare extracted balances with the original bank statement when a variance is reported.",
      "Keep each uploaded statement as a separate audit session so later reports remain traceable."
    ].forEach((item) => {
      const lines = doc.splitTextToSize(`- ${item}`, 760);
      doc.text(lines, 40, y);
      y += lines.length * 10 + 8;
    });
    addTxnSection("Appendix: Full Transaction Register", audit.transactions || []);

    doc.save(`SoMAp_Bank_Audit_${audit.bankName || "Statement"}_${audit.year || ""}_${audit.id || Date.now()}.pdf`.replace(/[^\w.-]+/g, "_"));
  }

  global.SomapBankAuditPdf = { download };
})(window);
